name: Build and unit test

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build
