name: Scheduled test job

on:
  schedule:
    - cron: '8 9 * * *'
    - cron: '10 9 * * *'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

